language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
# command to run tests
script:
  - pytest
  - coverage run pytest -v && coverage report
after_success:
  - coveralls
